
gems:
  - octopress-paginate
  - jekyll-feed

# Permalinks
permalink:           pretty

# Setup
timezone:            Asia/Jakarta # eg. Asia/Kathmandu
locale:              en_us # eg. en_us
name:				 The Play Dept.
title:               The Play Dept.
tagline:             Worth Noting Music.
description:         Daily curated of worth noting music
url:                 https://www.theplaydept.com/
rss:                 rss feed url
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_javascripts: '/assets/js/'
icon:                assets/images/mstile-310x310.png # /assets/img/icon.png [best 300px X 300px]
disqus:              disqus_shortname # get it on https://disqus.com/admin/

author:
  name:           	 The Play Dept.
  url:            	 https://www.theplaydept.com
  facebook:          theplaydept
  twitter:           theplaydept

fb_admins:           571184083005351
fb_appid:            236594396838887

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001


# Sass settings
sass:
    sass_dir: _scss
    style: :compressed

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
